env = Environment()

print "Environment:[" + env ['PLATFORM'] + "]"
if env ['PLATFORM'] == "posix":
	env['LINKFLAGS'] = '-Wl,-rpath=\'.\''

sharedlib = env.SharedLibrary('mylib', 'mylib.cpp')

program = env.Program('main.cpp', LIBS='mylib', 
	LIBPATH = ['.'])
  

